language: java
jdk:
- openjdk11
install: true
script:
- mvn spotless:check compile
notifications:
  slack:
    secure: idOzpwEsoWHminK7jC0qNTaMHE7Rb0R7ivDQsG9WQdNwHbHKJUMX1hgYRN7Bc/YlfA0U5GRqlKLxUTPIQvIx+bT+AxBJtSZgeM+vIeVI6avAc0P/27NEbl0IWyVp/HTUsQX8JJsmvm5Bf6x/6r1NXBn93DaqCOrGmHFF4+CQhXL5ta5lizePPhPDhRXOCkpRSeMockhgzjmltdQFmOX2oyosY2QXf2xVpCDbv0ZInan3lm3Rlh6t5vN0MkVMZ4tepNVnzZgS+k3pFZhMtq8PMDzSp7r7cUim3j8nr2eKJ9zHB/ABHmI/IEiN/BwNx85+BXmvdL1RD1PsKzQFtT8hPPpEiqb6dVkruVlZyOSN4gVVt45KrKNPbM2/inGeQZykflykdRqQHOSdn/oElLktwuTRAKgccr7aonOihwvKUOdD+EUsT1VpgeR43lIDe4Icc1vqmkgxT8Ha363OTyW9xfYn6N+ZQ3b2bQr5RuZwApungIY7RZ3oGbsuH92Mq6KZfoUQW4+5dvgiugpRziQXPekah6OfLj7BLAIHRPgU4uLyh44Ri0xgNnZYUg+qxUxAOfnywjfZxBRcVXybMoZLyzcXu1RF3ZJ/6hujyd3AbBFEWbnv0CbyVkQAeNr8eCc2xj4yzi1HgheBELS5LxvTuFBuuhmqh2JXqml0+KY90o4=
  webhooks:
    urls: 
      https://webhooks.gitter.im/e/2469f289a34ca37eed0c
    on_success: change
    on_failure: always
    on_start: never
